d = input('Precione qualquer tecla: ')

print('o tipo é ', type(d))
print(f'É númerico? {d.isnumeric()}')
print('É alfabetico?', d.isalpha())
print('É númerico?', d.isnumeric())
print('É um digito?', d.isdigit())
print('Começa com letra maiúscula e todas as outras caracteres são minuscula?', d.istitle())
print('É um está na tabela ASCII?', d.isascii())
print('É um numero decimal?', d.isdecimal())
print('É um palavra chave?', d.isidentifier())
print('É uma frase só com letra minuscula?', d.islower())
print('Tem como imprimir o que foi digitado ?', d.isprintable())
print('Contém apenas espaços?', d.isspace())
print('É um frase só com letra maiuscula?', d.isupper())
